### ISSUE TITLE
Question: Can the demo data be post-processed?

### ISSUE THREAD

**Issue by TravisBowers** [TensorWorks/Buccaneer#3]
When the demo runs, it creates two docker volumes. One of them is named `compose_eventslogs`. The named volume doesn't appear to contain any data collected from the stats server or events server. The un-named volume does appear to have _something_ written into the `chunks_head` and `wal` directories. Are these files comprehensive collections of the data that is being streamed to grafana? Can they be parsed or post processed after the demo has been terminated?

```
# docker volume ls
DRIVER    VOLUME NAME
local     1a45e44d1a5f44a1e279ebfddf8d0323c95593a46fefe294fdb1b49d351ba066
local     compose_eventslogs
root@ubuntu-20-04-2:/home/tcb/Buccaneer/Examples/Compose# ls -laR /var/lib/docker/volumes/1a45e44d1a5f44a1e279ebfddf8d0323c95593a46fefe294fdb1b49d351ba066/_data/*
-rw-r--r-- 1 nobody nogroup     0 Jun  3 16:15 /var/lib/docker/volumes/1a45e44d1a5f44a1e279ebfddf8d0323c95593a46fefe294fdb1b49d351ba066/_data/lock
-rw-r--r-- 1 nobody nogroup 20001 Jun  3 16:20 /var/lib/docker/volumes/1a45e44d1a5f44a1e279ebfddf8d0323c95593a46fefe294fdb1b49d351ba066/_data/queries.active

/var/lib/docker/volumes/1a45e44d1a5f44a1e279ebfddf8d0323c95593a46fefe294fdb1b49d351ba066/_data/chunks_head:
total 136
drwxr-xr-x 2 nobody nogroup   4096 Jun  3 16:19 .
drwxr-xr-x 4 nobody nogroup   4096 Jun  3 16:15 ..
-rw-r--r-- 1 nobody nogroup 131072 Jun  3 16:19 000001

/var/lib/docker/volumes/1a45e44d1a5f44a1e279ebfddf8d0323c95593a46fefe294fdb1b49d351ba066/_data/wal:
total 420
drwxr-xr-x 2 nobody nogroup   4096 Jun  3 16:15 .
drwxr-xr-x 4 nobody nogroup   4096 Jun  3 16:15 ..
-rw-r--r-- 1 nobody nogroup 418830 Jun  3 16:20 00000000
root@ubuntu-20-04-2:/home/tcb/Buccaneer/Examples/Compose# ls -laR /var/lib/docker/volumes/compose_eventslogs/_data/*
-rw-r--r-- 1 root root    0 Jun  3 16:15 /var/lib/docker/volumes/compose_eventslogs/_data/event.log
-rw-rw-r-- 1 root root  131 Apr 21 02:05 /var/lib/docker/volumes/compose_eventslogs/_data/go.mod
-rw-rw-r-- 1 root root 6484 Apr 21 02:05 /var/lib/docker/volumes/compose_eventslogs/_data/go.sum
-rw-rw-r-- 1 root root 1054 Apr 21 02:05 /var/lib/docker/volumes/compose_eventslogs/_data/main.go
```

**Comment by adamrehn** [comment]
@TravisBowers my understanding is that the underlying databases used by Prometheus and Loki aren't designed for consumption by external software, so you'll need to export the data to a common format before you can perform postprocessing with your analysis tools of choice. There are a few options available:

- Grafana allows you to download data directly through the [Inspector pane of the Explore page](https://grafana.com/docs/grafana/latest/explore/explore-inspector/). This supports exporting time-series data in CSV format and log data in TXT format. It's worth noting that this functionality does require some familiarity with using queries in Grafana, since a query must be run before its results can be downloaded. The visual query builder helps to make this marginally less daunting than writing raw queries from scratch, but there's still a learning curve involved.

- There's a tool called [Styx](https://github.com/go-pluto/styx) that uses the Prometheus [query API](https://prometheus.io/docs/prometheus/latest/querying/api/) to query the time-series database and export data to CSV format. This is easier to use for automation purposes, but still requires an understanding of Prometheus queries and cannot export semantic log events from Loki. The underlying HTTP API can also be used directly if you want to integrate query functionality into other software.
